### ISSUE TITLE
JsonRpcWebSocketClient should not handle errors in the constructor using executor

### ISSUE THREAD

**Issue by ftomassetti** [nubomedia-vtt/jsonrpc-ws-android#1]
Consider this constructor:

```
    public JsonRpcWebSocketClient(URI serverUri, WebSocketConnectionEvents events, LooperExecutor executor) {
        super(serverUri, new Draft_17());

        this.connectionState = WebSocketConnectionState.CLOSED;
        this.events = events;
        this.executor = executor;
    }
```

An error which happens in the call on the super constructor will happen while executor is null.

onError looks like this:

```
    @Override
    public void onError(final Exception e) {
        executor.execute(new Runnable() {
            @Override
            public void run() {
                if (connectionState != WebSocketConnectionState.ERROR) {
                    connectionState = WebSocketConnectionState.ERROR;
                    events.onError(e);
                }
            }
        });
    }
```

However executor could be null causing a NPE while we are handling an error. You may want to check if executor has been already assigned and think of a fall back strategy to manage this error.

**Comment by jpsjanne** [comment]
Hi, thanks for pointing this out. This issue has now been fixed and will be patched in version 1.0.6 shortly. No changes to API.

**Comment by ftomassetti** [comment]
thanks!

**Comment by jpsjanne** [comment]
Library has been committed to jCenter and Maven sync is in progress, ready within a couple of hours. A small correction to my previous statement, there has been API changes since I needed to change WebSocketClient from inheritance to composition. Therefore JsonRpcWebSocketClient has no methods available from org.java_websocket.client.WebSocketClient any longer, excluding setWebSocketFactory and getWebSocketFactory. In principal, end-users should not need to poke around with WebSocketClient , that's what the API is for. But if a need arises to access WebSocketClient, please issue another ticket.
